project:
  type: book

book:
  title: "ecoevo.social-docs"
  author: "Alexis Simon and github contributors"
  search: true
  repo-url: https://github.com/alxsimon/ecoevo.social-docs/
  repo-actions: [edit]
  sidebar:
    style: docked
  license: CC-BY-4.0
  chapters:
    - index.qmd
    - rules.qmd
    - etiquette.qmd
    - how-to-contribute.qmd

format:
  html:
    theme: cosmo
