project:
  type: book

book:
  title: "ecoevo.social-docs"
  author: <a href = https://github.com/alxsimon>Alexis Simon</a> and <a href = "https://github.com/alxsimon/ecoevo.social-docs/graphs/contributors">GitHub contributors</a>
  search: true
  repo-url: https://github.com/alxsimon/ecoevo.social-docs/
  repo-actions: [edit]
  sidebar:
    style: docked
  page-footer: |
    This work is licensed under a <br><a href = https://creativecommons.org/licenses/by/4.0/>Creative Commons Attribution 4.0 International License</a>
  license: CC-BY-4.0
  chapters:
    - index.qmd
    - rules.qmd
    - etiquette.qmd
    - staying-safe.qmd
    - tips.qmd
    - faq.qmd
    - how-to-contribute.qmd
    - contacts.qmd

format:
  html:
    theme: cosmo
    number-sections: false
